allow ud in correlation metadata app and remove dates
VEuPathDB/service-eda-compute pull request #82
Opened 2024-01-12 12:20 UTC by asizemore

For use with https://github.com/VEuPathDB/web-monorepo/pull/753 in the frontend

The current restrictions for the correlation assay x metadata app require datasets to have at least two entities. User datasets only have one entity, so they'll never get to see this correlation app. What a shame!

This PR lets the user datasets join the party by breaking up the check for appropriate metadata into two cases based on if the given entity has 0 or >=1 ancestors. If the entity has no ancestors, then we want to call "metadata" any variable on the entity that is not part of a collection. Once we have our metadata, we can apply the usual filters of `dataShape = CONTINUOUS` and so on.

Note this PR also adds an additional filter to remove dates from the candidate variables list.

2024-01-16 18:30 UTC, dmgaldi requested changes
Looks good! Left a few small comments

2024-01-16 18:30 UTC, dmgaldi commented on src/main/java/org/veupathdb/service/eda/compute/plugins/correlationassaymetadata/CorrelationAssayMetadataPlugin.java
> +          .collect(Collectors.toList());
Very minor, but if you want the filtering to all be together, you could move this below the definition of `variablesInACollection` and add a filter:

```
      metadataVariables = entity.getVariables().stream()
          .filter(var -> !var.getVariableId().contains("_stable_id"))
          .filter(var -> !variablesInACollection.contains(var))
          .collect(Collectors.toList());
```

2024-01-16 18:30 UTC, dmgaldi commented on src/main/java/org/veupathdb/service/eda/compute/plugins/correlationassaymetadata/CorrelationAssayMetadataPlugin.java
> +          .filter(var -> !var.getVariableId().contains("_stable_id")) // Filter out id variables
I *think* you can filter on `var.getVariableSource() != VariableSource.ID` instead of relying on this substring. The substring is probably fine in practice but it might just be a little more fragile since data dev might expect that code relies on that naming convention.

2024-01-16 18:30 UTC, dmgaldi commented on src/main/java/org/veupathdb/service/eda/compute/plugins/correlationassaymetadata/CorrelationAssayMetadataPlugin.java
> +    }
I think line 58-85 could be factored into a private method so you don't have to duplicate the code below.

2024-01-18 12:36 UTC, asizemore commented
Logic cleaned and new private method added! Thanks for the feedback @dmgaldi and it's ready for you to check out again!

2024-01-18 19:34 UTC, dmgaldi approved these changes
Looks good!

2024-01-19 10:53 UTC, merged